# Generated by Django 5.1.1 on 2024-10-16 23:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('borrowrecords', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='borrowrecord',
            unique_together={('user', 'book', 'returned')},
        ),
    ]
