# Generated by Django 5.1.1 on 2024-10-16 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrowrecords', '0003_alter_borrowrecord_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='borrowrecord',
            unique_together=set(),
        ),
    ]
