# Generated by Django 5.1.1 on 2024-10-14 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrecord',
            name='returned',
            field=models.BooleanField(default=False),
        ),
    ]
