# Generated by Django 5.1.1 on 2024-10-16 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_borrowrecord_returned'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BorrowRecord',
        ),
    ]
