# Generated by Django 5.1.1 on 2024-10-08 22:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_published_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='borrowrecord',
            unique_together={('user', 'book')},
        ),
    ]
